tlearning/__init__.py
from flask import Flask
from .uncertainty_apps import character_stratagy, cifar10h_app

dash_chara = character_stratagy.dash_application()
dash_cifar = cifar10h_app.dash_application()


def init_app():
    """Init the main application"""

    app = Flask(__name__, instance_relative_config=False)
    app.config.from_pyfile('config.py')

    dash_chara.init_app(app=app)
    dash_cifar.init_app(app=app)

    with app.app_context():  # structure
        # import routes
        from .home import routes as routes_home
        from .lm import routes as routes_lm
        from .logreg import routes as routes_logreg
        # blueprints
        app.register_blueprint(routes_home.home_bp)
        app.register_blueprint(routes_lm.lm_bp)
        app.register_blueprint(routes_logreg.logreg_bp)
        return app

tlearning/home/routes.py
from flask import Blueprint, render_template

# Blueprint Configuration
home_bp = Blueprint(
    'home_bp', __name__,
    template_folder='templates',
    static_folder='static',
    static_url_path='/home/static'
)


@home_bp.route('/', methods=['GET'])
def home():
    """Homepage."""
    return render_template(
        'index.html',
        title='Main page',
        subtitle='With a template',
        template='home-template',
    )

tlearning/lm/routes.py
from flask import Blueprint, render_template
from .lm_graphs import *

# Blueprint Configuration
lm_bp = Blueprint(
    'lm_bp', __name__,
    template_folder='templates',
    static_folder='static',
    static_url_path='/lm/static'
)


@lm_bp.route('/lm/concept_lm', methods=['GET'])
def lm():
    """Linear model page."""

    return render_template(
        'index_lm.html',
        title='LM main page',
        template='lm-template',
    )


@lm_bp.route('/lm/coding_lm', methods=['GET'])
def lm_code():
    """Code linear model page."""

    return render_template(
        'coding_lm.html',
        title='LM code page',
        template='lm-template',
    )


@lm_bp.route('/lm/playing_lm', methods=['GET'])
def lm_play():
    """Point and click linear model page."""

    return render_template(
        'playing_lm.html',
        title='LM GUI play page',
        template='lm-template',
    )


@lm_bp.route('/lm/math_lm', methods=['GET'])
def lm_math():
    """Some maths for the linear model page."""

    return render_template(
        'math_lm.html',
        title='LM math page',
        template='lm-template',
    )

tlearning/logreg/routes.py
from flask import Blueprint, render_template, request
from .logreg_graphs import *
from .models_code.pytorch_cifar import Logreg, test_dataset, classes
import torch
import os
import matplotlib.pyplot as plt
import numpy as np

file_dir = os.path.dirname(__file__)

# Blueprint Configuration
logreg_bp = Blueprint(
    'logreg_bp', __name__,
    template_folder='templates',
    static_folder='static',
    static_url_path='/logreg/static'
)


@logreg_bp.route('/logreg/concept_logreg', methods=['GET'])
def logreg():
    """Logistic model page."""

    return render_template(
        'index_logreg.html',
        title='logreg main page',
        template='logreg-template',
    )


@logreg_bp.route('/logreg/classification', methods=['GET'])
def logreg_code():
    """Classification with logistic regression page."""

    return render_template(
        'classification.html',
        title='Logreg code page',
        template='logreg-template',
    )


@logreg_bp.route('/logreg/multi_class', methods=['GET', 'POST'])
def logreg_multi():
    """Multi-class logreg classification."""
    if request.method == 'POST':
        idx_to_predict = request.form.to_dict()
        class_label, new_index = predict_tch(idx_to_predict["num"])
        return render_template(
            'multi_class.html',
            anchor="test",
            title='Multi class code page',
            template='logreg-template',
            prediction=class_label,
            index_=new_index
        )
    return render_template(
        'multi_class.html',
        anchor="main",
        title='Multi class code page',
        template='logreg-template',
        prediction="None yet",
        index_="None yet (enter a value!)"
    )


def predict_tch(idx_test):
    if idx_test == "":
        return "None", 1
    try:
        idx_test = int(idx_test)
    except ValueError:
        return "None", 1
    if idx_test >= 10000:
        return "None", 1
    else:
        path_model = os.path.join(file_dir, "models_code", 'data',
                                  'tch_model.pth')
        path_save = os.path.join(file_dir, 'static')
        model = Logreg(3*32*32, 10)
        optimizer = torch.optim.SGD(model.parameters(), lr=1e-4)

        checkpoint = torch.load(path_model)
        model.load_state_dict(checkpoint['model_state_dict'])
        optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
        epoch = checkpoint['epoch']  # noqa
        loss = checkpoint['loss']  # noqa
        model.eval()
        img = test_dataset[idx_test][0]
        out = model(img.view(-1, 3*32*32))
        _, predicted = torch.max(out.data, 1)
        img = img / 2 + 0.5     # unnormalize
        npimg = img.numpy()
        plt.imshow(np.transpose(npimg, (1, 2, 0)))
        plt.axis('off')
        plt.savefig(os.path.join(path_save, "cifar_img.png"))
        return classes[predicted], idx_test

tlearning/utils/__init__.py
from . import cifar10h

tlearning/utils/character_simulator/__init__.py
from . import villain
from . import citizen
from . import wizard

tlearning/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!--Plotly-->
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  <script type="text/javascript" async
    src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-MML-AM_CHTML">
  </script>
  <!--Number headings-->
  <link href="../static/mycss.css" rel="stylesheet" />
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>{% block title %} {% endblock %}</title>
  {% block head %} {% endblock %}
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('home_bp.home')}}">Tlearning</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="nav nav-tabs">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
            aria-expanded="false">Linear model</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="/lm/concept_lm">Concept</a>
            <a class="dropdown-item" href="/lm/math_lm">Some maths</a>
            <a class="dropdown-item" href="/lm/coding_lm">Coding</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="/lm/playing_lm">Your turn</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
            aria-expanded="false">Logistic regression</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="/logreg/concept_logreg">Concept</a>
            <a class="dropdown-item" href="/logreg/classification">Classification</a>
            <a class="dropdown-item" href="/logreg/multi_class">Multi class</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
            aria-expanded="false">Web apps</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="/dashapp_cifar">CIFAR10H</a>
            <a class="dropdown-item" href="/dashapp_character">RPG strategies</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container">
    <div id="main">
    {% block content %} {% endblock %}
    </div>
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
  <script>
    var openbtn = document.getElementById("open");
    var closebtn = document.getElementById("close");
    var closewithin = document.getElementById("closewithin");
    openbtn.style.display = 'none';

    function openNav() {
        navbar = document.getElementById("Sidebar")
        navbar.style.visibility = "visible";
        main = document.getElementById("main")
        if ($(window).width() < 900) {
          navbar.style.height = "auto";
          main.style.marginLeft = "0";
        }
        else {
          navbar.style.height = "1000px";
          main.style.marginLeft = "200px";
        }
        navbar.style.opacity = "1";
        openbtn.style.display = 'none';
        closebtn.style.display = '';
    }

    openNav();

    function closeNav() {
        navbar = document.getElementById("Sidebar")
        main = document.getElementById("main")
        navbar.style.visibility = "hidden";
        navbar.style.opacity = "0";
        navbar.style.height = "0";
        if ($(window).width() > 900) {
          main.style.marginLeft = "0px";
        }
        openbtn.style.display = '';
        closebtn.style.display = 'none';
    }
  </script>

</body>

</html>